name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7
      - run: xcodebuild -scheme Stats -destination 'platform=macOS,arch=arm64' -configuration Release archive CODE_SIGNING_ALLOWED=NO ARCHS=arm64 ONLY_ACTIVE_ARCH=NO
